import "./App.css";
import { Helmet } from "react-helmet";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

function App() {
  return (
    <div>
      <Helmet>
        <title>Champflix | Movies and Films</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="champflix-logo.jpg" />
      </Helmet>
      <main>
        <Navbar />
        <div className="flex h-[94vh]"></div>
        <Footer />
      </main>
    </div>
  );
}

export default App;
